package spreedly.client.java.model;

public class Fields
{

    public static final String ADDRESS_1 = "address1";
    public static final String ADDRESS_2 = "address2";
    public static final String AMOUNT = "amount";
    public static final String ATTRIBUTE = "attribute";
    public static final String AVS_CODE = "avs_code";
    public static final String AVS_MESSAGE = "avs_message";
    public static final String CANCELLED = "cancelled";
    public static final String CARD_TYPE = "card_type";
    public static final String CITY = "city";
    public static final String COUNTRY = "country";
    public static final String CREATED_AT = "created_at";
    public static final String CURRENCY_CODE = "currency_code";
    public static final String CVV_CODE = "cvv_code";
    public static final String CVV_MESSAGE = "cvv_message";
    public static final String DATA = "data";
    public static final String DESCRIPTION = "description";
    public static final String ELIGIBLE_FOR_CARD_UPDATER = "eligible_for_card_updater";
    public static final String EMAIL = "email";
    public static final String ERROR = "error";
    public static final String ERROR_CODE = "error_code";
    public static final String ERROR_DETAIL = "error_detail";
    public static final String ERRORS = "errors";
    public static final String FIRST_NAME = "first_name";
    public static final String FIRST_SIX_DIGITS = "first_six_digits";
    public static final String FULL_NAME = "full_name";
    public static final String GATEWAY_TOKEN = "gateway_token";
    public static final String GATEWAY_TRANSACTION_ID = "gateway_transaction_id";
    public static final String IP = "ip";
    public static final String KEY = "key";
    public static final String LAST_FOUR_DIGITS = "last_four_digits";
    public static final String LAST_NAME = "last_name";
    public static final String MERCHANT_LOCATION_DESCRIPTOR = "merchant_location_descriptor";
    public static final String MERCHANT_NAME_DESCRIPTOR = "merchant_name_descriptor";
    public static final String MESSAGE = "message";
    public static final String MONTH = "month";
    public static final String NUMBER = "number";
    public static final String ON_TEST_GATEWAY = "on_test_gateway";
    public static final String ORDER_ID = "order_id";
    public static final String PAYMENT_METHOD = "payment_method";
    public static final String PAYMENT_METHOD_ADDED = "payment_method_added";
    public static final String PAYMENT_METHOD_TOKEN = "payment_method_token";
    public static final String PAYMENT_METHOD_TYPE = "payment_method_type";
    public static final String PENDING = "pending";
    public static final String PHONE_NUMBER = "phone_number";
    public static final String REFERENCE_TOKEN = "reference_token";
    public static final String RESPONSE = "response";
    public static final String RETAIN_ON_SUCCESS = "retain_on_success";
    public static final String SHIPPING_ADDRESS_1 = "shipping_address1";
    public static final String SHIPPING_ADDRESS_2 = "shipping_address2";
    public static final String SHIPPING_CITY = "shipping_city";
    public static final String SHIPPING_COUNTRY = "shipping_country";
    public static final String SHIPPING_PHONE_NUMBER = "shipping_phone_number";
    public static final String SHIPPING_STATE = "shipping_state";
    public static final String SHIPPING_ZIP = "shipping_zip";
    public static final String STATE = "state";
    public static final String STORAGE_STATE = "storage_state";
    public static final String SUCCEEDED = "succeeded";
    public static final String SUCCESS = "success";
    public static final String TEST = "test";
    public static final String TOKEN = "token";
    public static final String TRANSACTION_TYPE = "transaction_type";
    public static final String TRANSACTION_TOKEN = "transaction_token";
    public static final String UPDATED_AT = "updated_at";
    public static final String VERIFICATION_VALUE = "verification_value";
    public static final String YEAR = "year";
    public static final String ZIP = "zip";

}
